### ISSUE TITLE
JS空格及换行

### ISSUE THREAD

**Issue by fengliner** [SOHU-Co/guidelines#2]
## 匿名函数function后是否要有空格，比如：

```
function(param1, param2) {
// doSomething
}
```

还是

```
function (param1, param2) {
// doSomething
}
```
## if语句是否必须要加{}，哪怕只有一行代码，比如：

```
if (err) {
  console.log(err);
}
```

还是

```
if (err) console.log(err);
```

另外，我觉得代码规范，最好是对某些典型的语句写一个example，这样看起来会比较清晰

**Comment by crzidea** [comment]
这两处地方不做硬性要求，主要是因为大家使用的编辑器的`snippets`插件可能不一样。例如[vim-snippets](https://github.com/honza/vim-snippets)中有两个snippets：
- [Function](https://github.com/honza/vim-snippets)
- [Anonymous Function](https://github.com/honza/vim-snippets/blob/master/snippets/javascript/javascript.snippets#L13)

其他编辑器可能还会有不同。我们尽量保持原有的风格不做修改。
另外，javascript的代码风格基本沿用[npm's "funny" coding style](https://docs.npmjs.com/misc/coding-style)。

**Comment by fengliner** [comment]
OK
